# Based on https://docs.haskellstack.org/en/stable/travis_ci/

sudo: false

language: generic

os:
  - osx
  - linux

# earlier clang versions may induce "symbols not found" errors
osx_image: xcode9.3

env:
  - RESOLVER="lts-11.22"          # ghc 8.2.2
  - RESOLVER="nightly-2018-06-26" # ghc 8.4.3
  - RESOLVER="lts-12.13"          # ghc 8.4.3
  - RESOLVER="nightly"

matrix:
  allow_failures:
    - env: RESOLVER="nightly"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxrandr-dev
    - libftgl-dev
    - libgmp-dev
    - portaudio19-dev
    # g++ versions before 7 won't work, as some needed C++17 features are not implemented.
    - g++-7
    - libstdc++-7-dev

cache:
  directories:
  - $HOME/.stack
  timeout: 1800

before_install:

- set -ex

- |
  if [[ $TRAVIS_OS_NAME == 'linux' ]]
  then
    export CXX=g++-7
    export CC=gcc-7
    ${CXX} --version
    ${CC} --version
    sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
    gcc --version
  fi
# We need to install clang on osx
- |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]
  then
    brew bundle --verbose
    brew info llvm
    brew update
    brew install llvm
    brew info llvm
    export CC="/usr/local/opt/llvm/bin/clang"
    export CXX="/usr/local/opt/llvm/bin/clang++"
    export LDFLAGS="-L/usr/local/opt/llvm/lib"
    export CPPFLAGS="-I/usr/local/opt/llvm/include"
    export PATH="/usr/local/opt/llvm/bin:$PATH"
  fi
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

- set +ex

# TODO use travis_wait 119
script:
- set -ex
- |
  echo "$(stack --resolver $RESOLVER exec -- which gcc)"
  echo "$(stack --resolver $RESOLVER exec -- gcc --version)"
- stack --no-terminal --resolver $RESOLVER build --install-ghc --only-dependencies -j2
# The doc of 'imj-audio' fails to build due to
#   https://github.com/haskell/cabal/issues/944
#   https://github.com/haskell/cabal/issues/4215
#- stack --no-terminal --resolver $RESOLVER test --pedantic --haddock --no-haddock-deps -j2
- stack --no-terminal --resolver $RESOLVER test --pedantic -j2
- set +ex
