# This is the complex Travis configuration, which is intended for use
# on open source libraries which need compatibility across multiple GHC
# versions, must work with cabal-install, and should be
# cross-platform. For more information and other options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

language: generic

os:
  - osx
  - linux

env:
  - RESOLVER="--resolver lts-11.5"
  - RESOLVER="--resolver nightly-2018-04-20"
  - RESOLVER="--resolver nightly"

allow_failures:
  - env: RESOLVER="--resolver nightly"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libxcursor-dev
    - libxi-dev
    - libxinerama-dev
    - libxrandr-dev
    - libftgl-dev
    - libgmp-dev
    - portaudio19-dev
    - g++-7
    - libstdc++-7-dev

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

before_install:
- |
  if [[ $TRAVIS_OS_NAME == 'linux' ]]
  then
    export CXX=g++-7
    export CC=gcc-7
    ${CXX} --version
    ${CC} --version
    sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
    gcc --version
  fi
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
  echo 'jobs: $ncpus' >> $HOME/.cabal/config

install:
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew bundle --verbose; fi
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi
- |
  set -ex
  echo "$(stack exec -- which gcc)"
  echo "$(stack exec -- gcc --version)"
  stack --no-terminal --install-ghc $RESOLVER test --bench --only-dependencies -j1
  set +ex

script:
- |
  set -ex
  stack --no-terminal $RESOLVER test --pedantic --bench --no-run-benchmarks --haddock --no-haddock-deps -j1
  set +ex
